### PR TITLE
Origins are at most eight bytes

### PR DESCRIPTION
**Pull request by fractalcat**
WIP, do not merge.

See also anchor/vaultaire#73.

### CODE REVIEW

**Comment by fractalcat** [comment]
Actually, I think this is good for now. I'd like to unexport the Origin constructor, but we'll need to make some accompanying changes to Vaultaire which I think we can sneak into a refactor of the read/write functions.

**Comment by afcowie** [comment]
It's good.

Do we need a more specific error response than "bad origin"?

**Comment by oswynb** [comment]
Could be useful:

OriginLengthTooLong
OriginContainsInvalidChars
OriginIsEmptyString

Or something along those lines?

**Comment by fractalcat** [comment]
@afcowie how's that?

**Comment by afcowie** [comment]
@fractalcat just replying "it's a bad origin" without saying what the [validation] problem is seems a tad unfriendly, no?

**Comment by fractalcat** [comment]
@afcowie I agree; I was asking what you thought of the change to that in the most recent commit.

**Comment by afcowie** [comment]
@fractalcat ah! Yes, looks great.

**Comment by afcowie** [comment]
@fractalcat separately, I wonder if you shouldn't just make BadOrigin an instance of Exception, rather than wrapping it into SomeException...

**Comment by fractalcat** [comment]
@afcowie: `BadOrigin` is an instance of `Exception`; `SomeException e` has this as an existential qualifier. Can't use `BadOrigin` on its own unless we wrap it in `SomeException` later due to using `Either SomeException` everywhere during unpacking.

**Comment by fractalcat** [comment]
Merge approved by @christian-marie and @tranma.

**Pull request merged**
